 
 
const allFoods = [
  {
    title: "Tarragon-Rubbed-Salmon",
    img: "https://i.postimg.cc/V6CFzzPS/lunch1.png",
    tag: "lunch",
    price: 6.99,
    p: "How we dream about out future",
    id: 1,
  },
  {
    title: "Honey-Soy-Glazed salmon width Peppers",
    img: "https://i.postimg.cc/R037TvFP/lunch2.png",
    tag: "lunch",
    price: 7.99,
    p: "How we dream about out future",
    id:2,
  },
  {
    title: "Fried Chicken bento",
    img: "https://i.postimg.cc/h4YCF3FQ/lunch3.png",
    tag: "lunch",
    price: 9.99,
    p: "How we dream about out future",
    id:3,
  },
  {
    title: "Beef Steak",
    img: "https://i.postimg.cc/fb6x21SM/lunch4.png",
    tag: "lunch",
    price: 15.99,
    p: "How we dream about out future",
    id:4,
  },
  {
    title: "Healthy Meal Plan",
    img: "https://i.postimg.cc/kGkGqd95/dinner6.png",
    tag: "lunch",
    price: 22.99,
    p: "How we dream about out future",
    id:5,
  },
  {
    title: "Indian Lunch",
    img: "https://i.postimg.cc/9FVBj38M/lunch5.png",
    tag: "lunch",
    price: 8.99,
    p: "How we dream about out future",
    id:6,
  },
  {
    title: "Bagel and cream cheese",
    img: "https://i.postimg.cc/8PHmpy9b/lunch6.png",
    tag: "breakfast",
    price: 6.99,
    p: "How we dream about out future",
    id:7,
  },
  {
    title: "Eggs Benedict",
    img: "https://i.postimg.cc/gkkNZFv7/breakfast1.png",
    tag: "breakfast",
    price: 8.99,
    id:8,
    p: "How we dream about out future",
  },
  {
    title: "Bucked chicken",
    img: "https://i.postimg.cc/NjZ4SKWh/breakfast2.png",
    tag: "breakfast",
    price: 7.99,
    p: "How we dream about out future",
    id:9,
  },
  {
    title: "Breakfast Sandwich",
    img: "https://i.postimg.cc/JzsxpNYc/breakfast3.png",
    tag: "breakfast",
    price: 9.99,
    p: "How we dream about out future",
    id:10,
  },
  {
    title: "Tost coheson",
    img: "https://i.postimg.cc/LsZy8tz6/breakfast4.png",
    tag: "breakfast",
    price: 15.99,
    p: "How we dream about out future",
    id:11,
  },
  {
    title: "Full Breakfast Fried Egg Toast Briunch",
    img: "https://i.postimg.cc/gjG4s11n/breakfast5.png",
    tag: "breakfast",
    price: 4.99,
    p: "How we dream about out future",
    id:12,
  },
  {
    title: "Baked chicken",
    img: "https://i.postimg.cc/52Wyr1n7/dinner1.png",
    tag: "dinner",
    price: 6.99,
    p: "How we dream about out future",
    id:13,
  },
  {
    title: "Pork Tenderloin with quinoa Pilaf",
    img: "https://i.postimg.cc/g2yjF57Y/dinner2.png",
    tag: "dinner",
    price: 14.99,
    p: "How we dream about out future",
    id:14,
  },
  {
    title: "Salmon with grapefruit and Lentil Salad",
    img: "https://i.postimg.cc/tCx7D7tn/dinner3.png",
    tag: "dinner",
    price: 12.99,
    id:15,
    p: "How we dream about out future",
  },
  {
    title: "French fries and cheese",
    img: "https://i.postimg.cc/tTv7vxMW/dinner4.png",
    tag: "dinner",
    price: 8.99,
    p: "How we dream about out future",
    id:16,
  },
  {
    title: "Lemony Salmon Piccata",
    img: "https://i.postimg.cc/9XSrGyTj/dinner5.png",
    tag: "dinner",
    price: 10.99,
    p: "How we dream about out future",
    id:17,
  },
  {
    title: "Garlic and Butter",
    img: "https://i.postimg.cc/kGkGqd95/dinner6.png",
    tag: "dinner",
    price: 6.99,
    p: "How we dream about out future",
    id:18,
  },
];
export default allFoods